---

- name: 'download the Go tarball'
  get_url: url={{ go_download_location }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}
           validate_certs=no
  tags:
    - golang

- name: 'register the current Go version (if any)'
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false
  tags:
    - golang

- name: 'extract the Go tarball'
  command: tar -C /usr/local -xf /usr/local/src/{{ go_tarball }}
  when: go_version|failed or go_version.stdout != go_version_target
  tags:
    - golang

- name: 'add the Go bin directory to the PATH variable for all users'
  copy: src=go-bin.sh
        dest=/etc/profile.d
  tags:
    - golang

- name: 'set GOPATH for all users'
  copy: src=go-path.sh
        dest=/etc/profile.d
  tags:
    - golang

- name: 'test the presence of Go'
  command: /usr/local/go/bin/go version
  tags:
    - golang
    - test