---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=2.1.0.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Install dependencies.
  - make setup
  - ansible-playbook install.yml -vv

script:
  - ansible --version
  - ansible-playbook --syntax-check provision.yml
  - ansible-playbook --list-hosts provision.yml
  - ansible-playbook -i travis.ini --check provision.yml
  - chmod 700 files
  - chmod 600 files/vagrant.rsa
