#!/usr/bin/env ansible-playbook -v

# Some roles are decoupled from this repository.
# These roles can reside in Github and/or Galaxy.

- name: "galaxy_import.yml"
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: 'install roles from galaxy'
      command: ansible-galaxy install -p ./roles_galaxy --role-file requirements.yml
