---
- name: Jenkins Master
  hosts: build
  sudo: yes

  roles:
#    - httpd
#    - firewall
    - jenkins                           # Use Jenkins to build
    - hullufred.nexus                   # Nexus is used as library repository
    - pcextreme.mariadb                 # Artifactory & sonar use mariadb
    - bbaassssiiee.artifactory          # Artifactory is our build repository
#    - bbaassssiiee.sonar                # SonarQube reports on code quality


- name: Selenium Grid Hub
  hosts: hub
  sudo: True
  gather_facts: yes

  roles:
    - httpd
    - ansible-selenium-role

- name: Slave servers
  hosts: slave
  sudo: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  roles:
    - ansible-jenkins-slave

