---
- name: 'run ad-hoc playbook'
  hosts: target:dev
  remote_user: vagrant
  sudo: yes
  gather_facts: yes

  pre_tasks:
    - name: 'add "nolio" in /etc/hosts file'
      lineinfile: dest=/etc/hosts regexp='192.168.10.36'
              line='192.168.10.36   nolio'
              state=present

  roles:
    - ansible-role-nolioagent

