#!/usr/bin/env ansible-playbook
- name: Build Server
  hosts: buildserver
  become: yes

  roles:
    - { role: ntp, tags: 'ntp' }
    - { role: epel, tags: 'epel' }
    - { role: bbaassssiiee.base_cplusplus, tags: 'cplusplus' }
    - { role: bbaassssiiee.base_java8, tags: 'java8' }
    - { role: bbaassssiiee.base_python, tags: 'python' }
    - { role: perl, tags: 'perl' }
    - { role: git, tags: 'git' }
    - { role: ant, tags: 'ant' }
    - { role: maven, tags: 'maven' }
    - { role: gradle, tags: 'gradle' }
    - { role: postgres, tags: 'postgres' }
    - { role: ansible, tags: 'ansible' }
    - { role: jenkins, tags: 'jenkins' }
    - { role: httpd, tags: 'httpd' }
#   - { role: hullufred.nexus, tags: 'nexus' } # symlink issue
    - { role: bbaassssiiee.artifactory, tags: 'artifactory' } # for built stuff
#   - { role: ansible-selenium-role, tags: 'ansible-selenium-role' }
    - { role: bbaassssiiee.sonar, tags: 'sonar' }

  tasks:
    - include: tasks/settings.yml

- name: system under test
  hosts: target
  remote_user: vagrant
  become: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  roles:
    - common
    - ntp
    - bbaassssiiee.base_java8
    - docker
#   - base_tomcat

#  tasks:
#    - include: tasks/tomcat_settings.yml

- name: test system
  hosts: test_slave
  remote_user: vagrant
  become: yes
  gather_facts: yes

  roles:
    - bbaassssiiee.base_java8
#    - ansible-selenium-role
    - ansible-jenkins-slave

- name: Windows client
  hosts: win_slave
  remote_user: IEUser
  gather_facts: no

  roles: []
#  - ansible-oasis
#  - ferhaty.jenkins-slave
#  - windows-selenium-role


