#!/usr/bin/env ansible-playbook
- name: Build Server
  hosts: build
  become: yes

  roles:
    - { role: base_ntp, tags: 'ntp' }
    - { role: base_cplusplus, tags: 'cplusplus' }
    - { role: base_perl, tags: 'perl' }
    - { role: base_python, tags: 'python' }
    - { role: base_git, tags: 'git' }
    - { role: base_java8, tags: 'java8' }
    - { role: base_ant, tags: 'ant' }
    - { role: base_maven, tags: 'maven' }
    - { role: base_gradle, tags: 'gradle' }
    - { role: base_golang, tags: 'golang' }
    - { role: base_postgres, tags: 'postgres' }
    - { role: base_ansible, tags: 'ansible' }
    - { role: jenkins, tags: 'jenkins' }
    - { role: httpd, tags: 'httpd' }

  tasks:
    - include: tasks/settings.yml

- name: system under test
  hosts: target_slave
  remote_user: vagrant
  become: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  roles:
    - base_common
    - base_common
    - base_ntp
    - base_java8
#   - base_tomcat
#    - ansible-jenkins-slave
#    - ansible-selenium-role

#  tasks:
#    - include: tasks/tomcat_settings.yml
#    - include: tasks/install_docker.yml

- name: test system
  hosts: test_slave
  remote_user: vagrant
  become: yes
  gather_facts: yes

  roles:
    - base_java8
#    - ansible-selenium-role
#    - ansible-jenkins-slave

- name: Windows client
  hosts: win_slave
  remote_user: IEUser
  gather_facts: no

  roles: []
#  - ansible-oasis
#  - ferhaty.jenkins-slave
#  - windows-selenium-role


