---
- name: Build Server
  hosts: dev:lab
  remote_user: vagrant
  sudo: yes

  roles:
    - bbaassssiiee.commoncentos
    - common
    - httpd
    - firewall
    - jenkins                           # Use Jenkins to build
    - hullufred.nexus                   # Nexus is used as library repository
    - geerlingguy.java
    - pcextreme.mariadb                 # Artifactory & sonar use mariadb
    - bbaassssiiee.artifactory          # Artifactory is our build repository
#    - bbaassssiiee.sonar                # SonarQube reports on code quality
    - ansible-selenium-role

  tasks:
    - include: tasks/settings.yml


- name: Target server
  hosts: target
  remote_user: vagrant
  sudo: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  pre_tasks:
    - include: tasks/settings.yml

  roles:
    - bbaassssiiee.commoncentos
    - common
    - geerlingguy.java
    - hudecof.tomcat
    - postgres
    - ansible-jenkins-slave
    - ansible-selenium-role

  tasks:
    - include: tasks/tomcat_settings.yml
    - include: tasks/install_docker.yml

- name: Ubuntu Box
  hosts: ubuntu
  remote_user: vagrant
  sudo: yes
  gather_facts: yes

  roles:
#    - briancoca.oracle_java7
    - geerlingguy.java
    - ansible-maven
    - ansible-eclipse
    - ansible-selenium-role
    - ansible-jenkins-slave

- name: Windows client
  hosts: windows
  remote_user: IEUser
  gather_facts: no

  roles:
  - ansible-oasis
  - ferhaty.jenkins-slave
  - windows-selenium-role

  tasks:
    - include: tasks/windows_settings.yml

