---
- src: bbaassssiiee.commoncentos
  path: ./roles/

- src: hudecof.tomcat
  path: ./roles

- src: pcextreme.mariadb
  path: ./roles/

- src: bbaassssiiee.artifactory
  path: ./roles/

- src: bbaassssiiee.sonar
  path: ./roles/

- src: hullufred.nexus
  path: ./roles/

- src: geerlingguy.java
  path: ./roles/

- src: briancoca.oracle_java7
  path: ./roles

- src: https://github.com/bbaassssiiee/ansible-maven
  path: ./roles/

# alban.andrieu.eclipse runs local as root.
- src: https://github.com/bbaassssiiee/ansible-eclipse.git
  path: ./roles

- src: https://github.com/bbaassssiiee/ansible-ant.git
  path: ./roles

# deploy Nolio with nolio.yml
- src: https://github.com/bbaassssiiee/ansible-role-nolioagent
  path: ./roles/

# Setup Windows machine as a Jenkins slave
- src: https://github.com/ferhaty/ferhaty.jenkins-slave.git
  path: ./roles/
