---
- name: windows
  hosts: windows
  remote_user: vagrant

  tasks:
    - name: create directory for selenium
      win_file: dest={{selenium_dir}} state=directory owner=IEUser

    - name: download selenium
      sudo: False
      win_get_url: url={{download_url}} dest={{selenium_dir}}//selenium-server.jar

