#!/usr/bin/env ansible-playbook
- name: Build Server
  hosts: dev:lab
  gather_facts: no
  remote_user: vagrant
  become: yes

  tasks:

  - name: 'verify tcp listening socket for Apache'
    wait_for: port=443 timeout=80 delay=1

  - name: 'verify tcp listening socket for Postgres'
    wait_for: port=5432 timeout=30

  - name: 'verify tcp listening socket for Jenkins'
    wait_for: port=8080 timeout=30

  - name: 'verify tcp listening socket for Artifactory'
    wait_for: port=8081 timeout=30

  - name: 'verify tcp listening socket for Nexus'
    wait_for: port=8082 timeout=30

  - name: 'verify tcp listening socket for Sonar'
    wait_for: port=9000 timeout=10
    ignore_errors: yes

  - name: 'verify local import of pki/buildserverCA.cer'
    become: no
    changed_when: no
    local_action: get_url url=https://dev/ validate_certs=yes timeout=10 dest=/dev/null

  - name: 'verify https connectivity to Jenkins'
    become: no
    local_action: uri url=https://dev/jenkins/jobConfigHistory/ validate_certs=no status_code=200

  - name: 'verify https connectivity to Nexus'
    become: no
    local_action: uri url=https://dev/nexus/#welcome validate_certs=no status_code=200

  - name: 'verify https connectivity to Artifactory'
    become: no
    local_action: uri url=https://dev/artifactory/webapp/#/artifacts/browse/tree/General/ext-release-local 
                  status_code=200 validate_certs=no

  - name: 'verify https connectivity to Jenkins'
    become: no
    local_action: uri url=https://dev/jenkins/ method=GET validate_certs=no status_code=200

  - name: 'verify https connectivity to releases repository in Nexus'
    become: no
    local_action: uri url=https://dev/nexus/#view-repositories;releases~browsestorage \
          status_code=200 \
          validate_certs=no \
          method=HEAD

  - name: 'verify tcp listening socket for TomCat on target'
    wait_for: host=target port=8080 timeout=5

  - name: 'verify http connectivity to TomCat on target'
    become: no
    local_action: uri url=http://target:8080/ status_code=200
