---

### Gradle
- name: 'verify presence of Gradle'
  stat: path={{gradle_home}}/bin/gradle
  register: gradle_installed
  when: features.gradle
  tags:
    - gradle

- name: 'download Gradle'
  get_url: url={{gradle_url}} dest=~ validate_certs=no
  retries: 3
  when: features.gradle and not gradle_installed.stat.exists
  tags:
    - gradle

- name: 'create directory for Gradle installations'
  file: dest={{jenkins_tools}}/hudson.plugins.gradle.GradleInstallation
        state=directory owner=jenkins group=jenkins mode=0755
  tags:
    - gradle

- name: 'unzip Gradle'
  command: unzip -q -o  ~/{{gradle_zipfile}} -d {{jenkins_tools}}/hudson.plugins.gradle.GradleInstallation creates={{gradle_home}}
  when: features.gradle
  tags:
    - gradle

- name: 'install /etc/profile.d/gradle.sh'
  template: src=etc-profile-d-gradle-sh.j2 dest=/etc/profile.d/gradle.sh
          owner=root group=root mode=0644
  when: features.gradle
  tags:
    - gradle

- name: 'verify presence of Gradle download'
  stat: path=~/{{gradle_zipfile}}
  register: gradle_download
  when: features.gradle
  tags:
    - gradle

- name: 'cleanup Gradle download'
  file: dest=~/{{gradle_zipfile}} state=absent
  when: features.gradle and gradle_download.stat.exists
  tags:
    - gradle

- name: 'make sure Gradle directory is absent'
  file: dest={{gradle_home}} state=absent
  when: not features.gradle
  tags:
    - gradle

- name: 'copy simple build template'
  become: no
  template: src=build.gradle dest=~/build.gradle
  tags:
    - gradle
    - test

- name: 'Test for presence of Gradle'
  become: no
  stat: path={{gradle_home}}/bin/gradle
  tags:
    - gradle
    - test

- name: 'Test running Gradle'
  become: no
  command: "{{gradle_home}}/bin/gradle build"
  tags:
    - gradle
    - test

- name: 'remove Gradle test file'
  become: no
  file: dest=/home/deployer/build.gradle state=absent
  tags:
    - gradle
    - test

