---
# Add sonar repository
- include: repo.yml

# Install dependencies
- include: dependencies.yml

# Install sonar runner
- include: runner.yml

# Install sonar plugins
- include: plugins.yml

# Run configuration
- include: config.yml
