---

### Ant
- name: 'make sure directory for Ant exists'
  file: dest={{ant_home}} state=directory owner=root group=root mode=0755
  tags:
    - jenkins
    - ant

- name: 'verify presence of Ant'
  stat: path={{ant_home}}/bin/ant
  register: ant_installed
  when: features.ant
  tags:
    - jenkins
    - ant

- name: 'download Ant'
  environment: '{{ proxy_env }}'
  get_url: url={{ant_url}} dest=~
  retries: 3
  when: features.ant and not ant_installed.stat.exists
  tags:
    - jenkins
    - ant

- name: 'untar Ant'
  command: tar xfz ~/{{ant_tarfile}} -C {{jenkins_tools}}/hudson.tasks.Ant_AntInstallation creates={{ant_home}}/bin/ant
  when: features.ant and not ant_installed.stat.exists
  tags:
    - jenkins
    - ant

- name: 'install /etc/profile.d/ant.sh'
  template: src=etc-profile-d-ant-sh.j2 dest=/etc/profile.d/ant.sh
          owner=root group=root mode=0644
  when: features.ant
  tags:
    - jenkins
    - ant

- name: 'verify presence of Ant download'
  stat: path=~/{{ant_tarfile}}
  register: ant_download
  when: features.ant
  tags:
    - jenkins
    - ant

- name: 'cleanup Ant download'
  file: dest=~/{{ant_tarfile}} state=absent
  when: features.ant and ant_download.stat.exists
  tags:
    - jenkins
    - ant

- name: 'make sure Ant directory is absent'
  file: dest={{ant_home}} state=absent
  when: not features.ant
  tags:
    - jenkins
    - ant
