---
# Add jenkins repository
- include: repo.yml

# Install dependencies (git, svn, etc)
- include: dependencies.yml

# Install jenkins
- include: jenkins.yml

# Install build tools
- include: ant.yml
- include: maven.yml
- include: gradle.yml


# Run configuration
- include: config.yml

# Install jenkins command line tools
- include: cli.yml

# Install/update jenkins plugins
- include: plugins.yml

# Install demo job: game-of-life
- include: demo.yml




