---

- name: 'list plugins'
  become: yes
  shell: java -jar {{jenkins_cli}} -s http://localhost:8080/jenkins list-plugins | cut -f 1 -d ' '
  when: plugins is defined
  register: plugins_installed
  tags:
    - jenkins
    - plugins

- name: 'install/update plugins'
  become: yes
  command: java -jar {{jenkins_cli}} -s http://localhost:8080/jenkins install-plugin {{ item }}
  when: plugins_installed.changed and plugins_installed.stdout.find('{{ item }}') == -1
  with_items: '{{ plugins }}'
  notify:
    - 'restart jenkins'
  tags:
    - jenkins
    - plugins

- name: 'list plugins to be updated'
  become: yes
  shell: java -jar {{jenkins_cli}} -s http://localhost:8080/jenkins list-plugins | grep ')$' | cut -f 1 -d ' ' | sed ':a;N;$!ba;s/\n/ /g'
  register: plugins_updates
  tags:
    - jenkins
    - plugins

- name: 'update plugins'
  become: yes
  command: java -jar {{jenkins_cli}} -s http://localhost:8080/jenkins install-plugin {{ plugins_updates.stdout }}
  when: plugins_updates.stdout != ''
  notify:
    - 'restart jenkins'
  tags:
    - jenkins
    - plugins
