---
# Configure webserver
- include: config.yml

# Install files in document root
- include: site.yml

# Configure certificates
- include: certificates.yml


- include: iptables.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 6

- include: firewalld.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7
