---

- name: 'yum install packages for C++ development'
  yum: name={{item}} state=present
  with_items: "{{ cplusplusrpms }}"
  tags:
    - cplusplus

- name: 'copy test program'
  become: no
  copy: src=hello_world.cc dest=~/hello_world.cc
  tags:
    - cplusplus
    - test

- name: 'Hello testing c++ compiler'
  become: no
  command: c++ ~/hello_world.cc -o ~/hello
  tags:
    - cplusplus
    - test

- name: 'run hello world program'
  become: no
  command: ~/hello
  register: hello
  tags:
    - cplusplus
    - test

- name: 'Hello checking'
  become: no
  fail:
  when: '"Hello World!" not in hello.stdout'
  tags:
    - cplusplus
    - test

- name: 'remove files'
  become: no
  file: name={{ item }} state=absent
  with_items:
    - ~/hello_world.cc
    - ~/hello
  tags:
    - cplusplus
    - test